project_id = "ucwactkevbbvjujraqbz"

[functions.parse-sales]
verify_jwt = false

[functions.generate-prep-list]
verify_jwt = false

[functions.parse-master-menu]
verify_jwt = false

[functions.parse-par-sheet]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false
